# Generated by Django 5.1.4 on 2025-01-13 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deduction_amount', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('content_size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refill_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('refill_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.IntegerField()),
                ('referral_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('referral_payments', models.ManyToManyField(blank=True, to='api.referralpayment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referrer', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('avatar', models.CharField(choices=[('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3')], max_length=50)),
                ('tariff', models.IntegerField(choices=[(0, 'Free'), (1, 'Basic'), (2, 'Premium')], default=0)),
                ('balance', models.IntegerField(default=0)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('api_token', models.CharField(blank=True, null=True, max_length=128, unique=True)),
                ('deductions', models.ManyToManyField(blank=True, to='api.deduction')),
                ('referrals', models.ManyToManyField(blank=True, to='api.referral')),
                ('refills', models.ManyToManyField(blank=True, to='api.refill')),
            ],
        ),
    ]
